name: Deployment Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    
    - name: Lint Test
      run: |
        yarn install
        yarn run lint
        
    - name: Coverage Report
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.github_token }}
      run: |
        yarn install
        yarn run test:coveralls
      
    
